name: Artifact

on:
    push

jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/upload-artifact@v4
              with:
                name: uploaded #artifact名称
                path: data.txt
                retention-days: 1

    download:
        runs-on: ubuntu-latest
        needs: [upload]
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: uploaded
                path: downloaded
            - run: cat downloaded/data.txt
        