name: Hello                       # ワークフロー名
run-name: Run by ${{github.actor}}   # 実行名
on: 
  [push, pull_request]                        # イベント（プッシュ時に起動）

jobs:                             # ジョブの定義
  hello:                          # ジョブID
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:                        # ステップの定義
      - name: Checkout
        uses: actions/checkout@v4 # アクションの呼び出し
      - name: Hello
        run: echo "Hello, world"  # シェルコマンドの実行
      - name: print
        run: echo "username:${USERNAME}"
      - name: print password with mask
        run: echo "password:${PASSWORD}"
      - name: print password without mask
        run: echo "password:${PASSWORD:0:1} ${PASSWORD#?}"
      
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Json
        run: echo "${CONTEXT}" 
        env:
          CONTEXT: ${{ toJSON(github) }}
        
      - name: Conditional
        run: echo "Hello, world" 
        if: ${{ contains(github.run_id, '1') }}

  skip-or-run:
    if: ${{ github.actor == 'octocat' }}
    runs-on: ubuntu-latest
    steps:
      - name: skip-or-run
        run: echo "Hello, world"

  share:
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=source" >> "$GITHUB_OUTPUT" # 出力をファイルに書き込む
      - id: consume
        run: echo "consum ${RESULT}"
        env:
          RESULT: ${{ steps.source.outputs.result }}
  
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4 # リポジトリのチェックアウト
      - run: gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #GitHub CLIの仕様です。つまり次のように環境変数を定義すれば、GitHub CLIは自動的にクレデンシャルを読み込んでくれます。 