name: Hello                       # ワークフロー名
on: push                          # イベント（プッシュ時に起動）
jobs:                             # ジョブの定義
  hello:                          # ジョブID
    runs-on: ubuntu-latest        # ランナー（Ubuntuで実行）
    steps:                        # ステップの定義
      - name: Checkout
        uses: actions/checkout@v4 # アクションの呼び出し
      - name: Hello
        run: echo "Hello, world"  # シェルコマンドの実行
      - name: print username
        run: echo "username: ${{ vars.USERNAME }}"
