name: Static analysis
on:
  pull_request

defaults:
    run:
        shell: bash

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        env:
            NAME: ${{ github.actor }}
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - shell: bash
              run: |
                set -x
                set -e
                echo "Hello, world"
            - uses: actions/checkout@v4
            - run: docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest
            - shell: python
              run: |
                import os
                print(os.environ['NAME'])
                print(os.getcwd())
            - name: Check test.py with pylint
              run: |
                if [ -f "test.py" ]; then
                    set -x
                    python -m pip install pylint
                    python -m pylint test.py || echo "Pylint found issues, check the output above"
                else
                    echo "test.py not found"
                    exit 1
                fi
    
    # JOB依存関係を記述
    first-job:
        runs-on: ubuntu-latest
        needs: [lint]
        steps:
            - run: echo "lint job is done"
            - id: first_job
              run: echo "result=Hello, world" >> "${GITHUB_OUTPUT}"
        outputs:
            result: ${{ steps.first_job.outputs.result }}
    
    #JOBのデータ共有
    second-job:
        runs-on: ubuntu-latest
        needs: [first-job]
        steps:
            - env:
                RESULT: ${{ needs.first-job.outputs.result }}
              run: echo "${RESULT}"


            
