name: Static analysis
on:
  pull_request

defaults:
    run:
        shell: bash

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        env:
            NAME: ${{ github.actor }}
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - shell: bash
              run: echo "Hello, world"
            - uses: actions/checkout@v4
            - run: docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:latest
            - shell: python
              run: |
                import os
                print(os.environ['NAME'])

    