name: Manual Workflow

on: 
  workflow_dispatch:
    inputs:
      greeting:
        description: 'Enter your name'
        required: true
        default: 'World'
      log_level:
        description: 'Enter your log level'
        required: true
        type: choice
        options:
          - debug
          - info
          - warning
        default: 'info'

jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello, ${{ github.event.inputs.greeting }}"
      - name: Log
        run: echo "Log level ${{ github.event.inputs.log_level }}"